apiVersion: v1
kind: Service
metadata:
 name: abacate
spec:
  ports:
  - name: abacate
    protocol: TCP
    port: 8761
    targetPort: 80
    nodePort: 31852
  selector:
    name: abacate
    tier: backend
    app: abacate
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: abacate
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: abacate 
        tier: backend
        name: abacate
    spec:
      containers:
      - name: abacate
        image: localhost:5000/eurika-machine:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761


